version : "2"

services:
  influxdb:
     container_name: influxdb
     image: influxdb:1.2
     ports:
       - "8083:8083"
       - "8086:8086"
  
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    links:
      - influxdb

  telegraf:
    container_name: telegraf
    image: telegraf
    links:
      - influxdb
    volumes:
      - /home/vagrant/shared/telegraf.conf:/etc/telegraf/telegraf.conf

  kapacitor:
    container_name: kapacitor
    image: kapacitor:1.2.0
    ports:
      - "9092:9092"
    links:
      - influxdb
    volumes:
      - /home/vagrant/shared/kapacitor.conf:/etc/kapacitor/kapacitor.conf
